<img src="https://shwetkm.github.io/upxlogo.png"></img>

# Python Advanced - Data Science Foundation

**SET THE WORKING DIRECTORY SO THAT WE DO NOT HAVE TO THINK ABOUT PATH PROBLEMS**

Please ensure all your folder names <font color='red'><b>do not have a space & use forward slash (/)</b></font>

In [11]:
# Please ensure the path follows the rules we had discussed and ensure a '/' at the last
your_local_path="C:/Users/tejks/Desktop/ML/practice/"

In [12]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 - 1) * i
    return d

In [13]:
%timeit func_python(10000)

1.92 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
distance = [45,51,35]
speed = [5,10,7]
#time = distance/speed 
#print (time)

**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. <b>The advantage of using ndarray is that processing is extremely efficient and fast.</b> 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is <b>linear algebra, statistical operations, and other specialized mathematical operations</b>. For our purpose, we need to know about <b>ndarray and the range of mathematical functions that are relevant to our research purpose</b>. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of <b>NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work</b>. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:
<i>
+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics
</i>
**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [15]:
import numpy as np

The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [16]:
from numpy import array
from numpy import arange

In [17]:
dist = array(distance)
spd = array(speed)
dist

array([45, 51, 35])

In [18]:
# How we have overcome the prior challenge using 
dist = array(distance)
spd = array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
#len(time)

[45 51 35]
[ 5 10  7]
[9.  5.1 5. ]


ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can <b>perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops</b>. The way to initialize an array object is

In [19]:
a=[1,2,3,4,5]                                 # initialize a list and assign values to it
b=[10,20,30,40]
print (a + b)
#print (a + 5)                               #Want to add '5' to all the elements in the list
c = [val + 5 for val in a]           
print (c)

[1, 2, 3, 4, 5, 10, 20, 30, 40]
[6, 7, 8, 9, 10]


In [20]:
f = array([1,2,3,4,5])                       # initializes an array a and assigns values to it
g = array((10,20,30,40,50))                 # initializes another array b
#print (a)
#print (b)
print(f+g) 
print (f+5) 
f**2+g**3
f.sum()

[11 22 33 44 55]
[ 6  7  8  9 10]


15

In [21]:

multi_array = array(((1,4),(True,False),(3.5,4.5)))
print (multi_array)
multi_array.sum(axis=1)


[[1.  4. ]
 [1.  0. ]
 [3.5 4.5]]


array([5., 1., 8.])

In [22]:
c = array(arange(10))                           #arange function here works as a sequence or counter in increments of 1
print ('array:                ', c)
print()
print()

anarray = array(arange(5,55,5))                 #arange function here works as a sequence or counter in increments of 5
print ('anarray:              ', anarray)
print()
print()

onemorearray = array(np.linspace(1,10,4))          #linspace function here creates 11 evenly spaced numbers over a specified interval
print ('onemorearray:         ', onemorearray)
#print ('Rounded onemorearray: ', np.round(onemorearray,0))
#np.round(onemorearray,0).sum() #5 1 15 20 25 30 35 40 45 50 55

array:                 [0 1 2 3 4 5 6 7 8 9]


anarray:               [ 5 10 15 20 25 30 35 40 45 50]


onemorearray:          [ 1.  4.  7. 10.]


With each ndarray are associated two attributes: shape of the array, and type of the array. The <font color='red'><b>shape</b> of the array tells you about <b><u>dimensionality</u></b> of the array (rows and columns), and <b>type</b> of the array tells you about the <b><u>data type</u></b> contained</font> in the array.

In [23]:
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31,32,28,98,14,86,119))
#data3 = data.reshape(2,12)
data2 = data.reshape(5,6)
print(data2)
#print ("*****")
#print (data2)
print(data2.shape)
print(data2.dtype)
print(data2.size)
even_data = (data2 % 2 == 0)
print (even_data)
data2[even_data]

[[  32   45  123  756   23 2123]
 [   1    2    3    4    5    6]
 [   6    5    4    3    2    1]
 [  78   89   87   76   54   31]
 [  32   28   98   14   86  119]]
(5, 6)
int32
30
[[ True False False  True False False]
 [False  True False  True False  True]
 [ True False  True False  True False]
 [ True False False  True  True False]
 [ True  True  True  True  True False]]


array([ 32, 756,   2,   4,   6,   6,   4,   2,  78,  76,  54,  32,  28,
        98,  14,  86])

In [24]:
np.zeros((5,10))                         # Make a 50, 0 numbered single dimensional array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((3,5)) + 6                     # Make a 15, 0 numbered 2 dimensional array

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [26]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones(30) + 7                         # Make a 30, 1 numbered single dimensional array

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [28]:
np.ones((5,9))                       # Make a 45, 1 numbered 2 dimensional array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.eye(5) + 2                       # creates a 5*5 identity matrix. 

array([[3., 2., 2., 2., 2.],
       [2., 3., 2., 2., 2.],
       [2., 2., 3., 2., 2.],
       [2., 2., 2., 3., 2.],
       [2., 2., 2., 2., 3.]])

In [30]:
np.diag(array([1,3,5,3,4,5]))        # Populate the disgonal elements only

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [31]:
multi_array = np.array([(4,1,2),(5,8,9)])
c = multi_array.reshape(6,1)
c = multi_array.reshape(3,2)
print (c)

[[4 1]
 [2 5]
 [8 9]]


**pandas**

Pandas is the primary package for performing data analysis tasks in Python. pandas derives its name from <b>PANel Data AnalysiS</b> and is the fundamental package that provides <b>relational data structures (think Excel, SQL type) and a host of capabilities to play with those data structures</b>. It is the most widely used package in Python for data analysis tasks, and is very good to work with <b>cross sectional, time series, and panel data analysis</b>. Python sits on top of NumPy and can be used with NumPy arrays and the functions in NumPy. How is pandas suited for a researcher’s needs:
<i>
+ Has a tabular data structure that can hold both <b>homogenous and heterogenous data</b>.
+ Very <b>good indexing capabilities</b> that makes data alignment and merging easy.
+ Good <b>time series functionality</b>. No need to use different data structures for time series and cross sectional data. Allows for both <b>ordered and unordered time-series data</b>.
+ A host of <b>statistical functions</b> developed around NumPy and pandas that makes a researcher’s task easy and fast.
+ Programming is lot <b>simpler and faster</b>.
+ Easily handles <b>data manipulation and cleaning</b>.
+ Easy to expand and shorten data sets. <b>Comprehensive merging, joins, and group by functionality to join multiple data sets</b>.
</i>

**Installing pandas** 

In order to check if pandas is installed, go to Package Manager and type pandas. By default, pandas already comes installed with a distribution of Canopy. If the package is not installed, click on Install.

**Importing pandas**

In order to be able to use NumPy, first import it using import statement


In [32]:
import pandas as pd                 # This will import pandas into your workspace

In [33]:
import numpy as np                          # We will be using numpy functions so import numpy

**Data Structures in pandas**

There are two basic data structures in pandas: <b><i>Series and DataFrame</i></b>

**Series:** It is similar to a NumPy 1-dimensional array. In addition to the values that are specified by the programmer, <b>pandas attaches a label to each of the values</b>. If the labels are not provided by the programmer, then pandas assigns labels ( 0 for first element, 1 for second element and so on). A benefit of assigning labels to data values is that it becomes easier to perform manipulations on the dataset as the whole dataset becomes more of a dictionary where each value is associated with a label. 


In [34]:
series1 = pd.Series(['10','20','30','40'])
series1

0    10
1    20
2    30
3    40
dtype: object

In [35]:
series1.values

array(['10', '20', '30', '40'], dtype=object)

In [36]:
series1.index

RangeIndex(start=0, stop=4, step=1)


If you want to specify custom index values rather than the default ones provided, you can do so using the following command

In [1]:
import pandas as pd
series2 = pd.Series([10,20,30,40], index=['Sai','teaching',1,'students'])
series2

Sai         10
teaching    20
1           30
students    40
dtype: int64

In [38]:
series2.index

Index(['Sai', 'teaching', 'python', 'students'], dtype='object')

The ways of accesing elements in a Series object are similar to what we have seen in NumPy, and you can perform NumPy operations on Series data arrays.

In [39]:
seq=(39.6,42,43,41,31,12)
index=(1,3,5,7,9,11)
ser=pd.Series(seq,index)
print (ser)
ser[0]

1     39.6
3     42.0
5     43.0
7     41.0
9     31.0
11    12.0
dtype: float64


KeyError: 0

In [40]:
pd.show_versions(as_json=False)


INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None


In [41]:
series2

Sai         10
teaching    20
python      30
students    40
dtype: int64

In [42]:
series2['python']                  # How to print 30 from the series

30

In [43]:
#series2[['one', 'three', 'five']]

In [4]:
print (series2)

Sai         10
teaching    20
1           30
students    40
dtype: int64


In [6]:
series2['1']

KeyError: '1'

In [46]:
series2[[1,3,5]]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [7]:
series2 + 4            # Add 4 to every element

Sai         14
teaching    24
1           34
students    44
dtype: int64

In [47]:
series2 ** 3           # Cube every element 

Sai          1000
teaching     8000
python      27000
students    64000
dtype: int64

In [48]:
series2>30

Sai         False
teaching    False
python      False
students     True
dtype: bool

In [49]:
series2[series2>30]    # Find all values greater than 30

students    40
dtype: int64

In [50]:
pd.sqrt(series2)       # Get the square roots of all the values

AttributeError: module 'pandas' has no attribute 'sqrt'

If you have a dictionary, you can <b>create a Series data structure from that dictionary</b>. Suppose you are interested in EPS values for firms and the <i>values come from different sources and is not clean. In that case you dont have to worry about cleaning and aligning those values</i>. 

In [51]:
years = [91, 90, 92, 'Sai']
f1 = {91:8, 90:9, 82:7, 'Sai':8, 50:11, 60:13}
firm1 = pd.Series(f1,index=years)                     # Extra element in VALUE not an issue
firm1.isnull()
#firm1

91     False
90     False
92      True
Sai    False
dtype: bool

In [52]:
f2 = {92:'Charan',92:14, 93:'Sai', 94:5}                      
firm2 = pd.Series(f2,index=years)                   # Extra element in the KEY is handled as NaN
firm2

91     NaN
90     NaN
92      14
Sai    NaN
dtype: object

NaN stands for missing or NA values in pandas. Make use of isnull() function to find out if there are any missing values in the data structure.

In [53]:
pd.isnull(firm2)

91      True
90      True
92     False
Sai     True
dtype: bool

A key feature of Series data is structures is that you don't have to worry about data alignment. For example, if we have run a word count program on two different files and we have the following data structures

In [54]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print (count1)
print (count2)
count1+count2

finance    10
earning     5
debt        8
dtype: int64
finance         8
compensation    4
earning         9
dtype: int64


compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

If we want to calculate the sum of common words in combined files, then we dont have to worry about data alignment. If we want to include all words, then we can take care of NaN values and compute the sum. By default, Series data structure ignores NaN values. NaN values stand for missing data values.

In [55]:
dict1+dict2                                # Sum values on key based retrieval. Non matching keys become NaN

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

**Data Frame**

DataFrame is a <b>tabular data structure</b> in which data is laid out in <b>rows and column</b> format (similar to a CSV and SQL file), but it can also be <b>used for higher dimensional data</b> sets. The DataFrame object can contain homogenous and heterogenous values, and can be thought of as a logical extension of Series data structures. In contrast to <u>Series</u>, where there is <b>one index</b>, a <u>DataFrame</u> object has <b>one index for column and one index for rows</b>. This allows flexibility in accessing and manipulating data.

In [56]:
import pandas as pd
import numpy as np
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
print (data)
data.iloc[1:3,1:2]

   price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart


ticker
1   CSCO
2    DIS

In [57]:
data.loc[1:3,'price':'company']

price ticker      company
1     25   CSCO        Cisco
2     85    DIS  Walt Disney
3     41   MSFT    Microsoft

If a column is passed with no values, it will simply have NaN values

In order to access a column, simply mention the column name

In [58]:
data['company']                          # Print only company names

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [59]:
data.company                            # Another way to print only company names

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [60]:
print (data.ix[2])                              # Print the row corresponding to the given Index

price               85
ticker             DIS
company    Walt Disney
Name: 2, dtype: object


C:\Users\tejks\anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [61]:
data.ticker == 'DIS'

0    False
1    False
2     True
3    False
4    False
Name: ticker, dtype: bool

In [62]:
data.ix[data.ticker == 'DIS']            # Print the row corresponding to the ticker that is 'DIS'

C:\Users\tejks\anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


price ticker      company
2     85    DIS  Walt Disney

In [63]:
data.iloc

In order to add additional columns

In [64]:
data['Year'] = 2013                       # Add additional column Year. Populate value of 2014 in all the rows.
data

price ticker           company  Year
0     95    AXP  American Express  2013
1     25   CSCO             Cisco  2013
2     85    DIS       Walt Disney  2013
3     41   MSFT         Microsoft  2013
4     78    WMT           Walmart  2013

In [65]:
data['pricesquared'] = data.price**2      # Square all the prices and add another column 'pricesquared'.
data

price ticker           company  Year  pricesquared
0     95    AXP  American Express  2013          9025
1     25   CSCO             Cisco  2013           625
2     85    DIS       Walt Disney  2013          7225
3     41   MSFT         Microsoft  2013          1681
4     78    WMT           Walmart  2013          6084

In [66]:
del data['pricesquared']                  # Delete column 'pricesquared'
data

price ticker           company  Year
0     95    AXP  American Express  2013
1     25   CSCO             Cisco  2013
2     85    DIS       Walt Disney  2013
3     41   MSFT         Microsoft  2013
4     78    WMT           Walmart  2013

In [67]:
data['pricesquared'] = np.NaN             # Create column 'pricesquared' with NaN values
data

price ticker           company  Year  pricesquared
0     95    AXP  American Express  2013           NaN
1     25   CSCO             Cisco  2013           NaN
2     85    DIS       Walt Disney  2013           NaN
3     41   MSFT         Microsoft  2013           NaN
4     78    WMT           Walmart  2013           NaN

In [105]:
data['year2'] = [2013,2014,2015,2016,2017]
data

price ticker           company  Year  pricesquared  sequence  year2
0     95    AXP  American Express  2013           NaN      2014   2013
1     25   CSCO             Cisco  2013           NaN      2016   2014
2     85    DIS       Walt Disney  2013           NaN      2018   2015
3     41   MSFT         Microsoft  2013           NaN      2020   2016
4     78    WMT           Walmart  2013           NaN      2022   2017

In [69]:
data['sequence'] = np.arange(2014,2024,2)         # Add column 'sequence' and populate sequence of numbers from 1 to 5
data

price ticker           company  Year  pricesquared  sequence
0     95    AXP  American Express  2013           NaN      2014
1     25   CSCO             Cisco  2013           NaN      2016
2     85    DIS       Walt Disney  2013           NaN      2018
3     41   MSFT         Microsoft  2013           NaN      2020
4     78    WMT           Walmart  2013           NaN      2022

In [70]:
data.loc[1:3,'ticker':'Year']

ticker      company  Year
1   CSCO        Cisco  2013
2    DIS  Walt Disney  2013
3   MSFT    Microsoft  2013

In [71]:
data.loc[2,'Year']

2013

In [72]:
data.iloc[1:3,1:4]

ticker      company  Year
1   CSCO        Cisco  2013
2    DIS  Walt Disney  2013

In [75]:
add_record=pd.DataFrame({'price':[54],'ticker':['APPLE'],'company':['APPLE'],'Year':[2012],'pricesquared':[12],'sequence':[2012]})

In [91]:
add_record

price ticker company  Year  pricesquared  sequence
0     54  APPLE   APPLE  2012            12      2012

In [99]:
data2=data.append(add_record)

In [100]:
data2

price ticker           company  Year  pricesquared  sequence
0     95    AXP  American Express  2013           NaN      2014
1     25   CSCO             Cisco  2013           NaN      2016
2     85    DIS       Walt Disney  2013           NaN      2018
3     41   MSFT         Microsoft  2013           NaN      2020
4     78    WMT           Walmart  2013           NaN      2022
0     54  APPLE             APPLE  2012          12.0      2012

In [103]:
data2.iloc[5]

price              54
ticker          APPLE
company         APPLE
Year             2012
pricesquared       12
sequence         2012
Name: 0, dtype: object

You can use NumPy functions inside DataFrame objects.

In [106]:
import numpy as np
import pandas as pd
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])  # Create array of 3*3 dimensionality using standard normally distributed random vales
dataframe

one       two     three
0 -0.436103 -1.325049  0.619804
1  0.351407 -0.620084  0.962171
2 -0.031450 -1.142839 -0.134600

In [107]:
np.abs(dataframe)                   # Absolute value

one       two     three
0  0.436103  1.325049  0.619804
1  0.351407  0.620084  0.962171
2  0.031450  1.142839  0.134600

In [108]:
f = lambda x:x.max()-x.min()        # We have option to use a powerful lambda function feature. Get the range in a column
abs(dataframe).apply(f)

one      0.404653
two      0.704964
three    0.827571
dtype: float64

In [109]:
abs(dataframe).apply(f,axis=1)           # Apply lambda function on the row and not column as we did in the previous example

0    0.888945
1    0.610764
2    1.111389
dtype: float64

In [151]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
print(abs(dataframe))
df3.apply(f)

        one       two     three
0  0.436103  1.325049  0.619804
1  0.351407  0.620084  0.962171
2  0.031450  1.142839  0.134600


Firm1  Firm2      Firm3
mean   8.666667  10.25  11.666667
max   11.000000  14.00  13.000000
min    7.000000   5.00  10.000000

In [155]:
np.random.uniform(3,9,5)

array([4.58675789, 3.11637566, 7.68424249, 3.19466214, 3.35412906])

In [115]:
print(dataframe)
dataframe.max(axis=1)                         # Column wise sum

        one       two     three
0 -0.436103 -1.325049  0.619804
1  0.351407 -0.620084  0.962171
2 -0.031450 -1.142839 -0.134600


0    0.619804
1    0.962171
2   -0.031450
dtype: float64

In [ ]:
dataframe.sum(axis=1)                    # Row wise sum

In [112]:
print(dataframe)
dataframe.cumsum()                 # Get cumulative sum

        one       two     three
0 -0.436103 -1.325049  0.619804
1  0.351407 -0.620084  0.962171
2 -0.031450 -1.142839 -0.134600


one       two     three
0 -0.436103 -1.325049  0.619804
1 -0.084696 -1.945133  1.581975
2 -0.116147 -3.087972  1.447375

In [116]:
dataframe.describe()


one       two     three
count  3.000000  3.000000  3.000000
mean  -0.038716 -1.029324  0.482458
std    0.393805  0.365934  0.561137
min   -0.436103 -1.325049 -0.134600
25%   -0.233777 -1.233944  0.242602
50%   -0.031450 -1.142839  0.619804
75%    0.159978 -0.881462  0.790987
max    0.351407 -0.620084  0.962171

If you have non-numeric data, then applying describe function would produce statistics such as <b>count, unique, frequency</b>. In addition to this, you can also calculate <b>skewness (skew), kurtosis (kurt), percent changes, difference, and other statistics</b>.

**Missing Data**

Pandas have a number of features to deal with <b>missing data</b>. We have seen an example of the case of descriptive statistics, where missing values are not taken into account while calculating the descriptive statistics. Missing data is denoted by NaN. 

In [118]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df3 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df3
df3.Firm1 = firm1
df3.Firm2 = firm2
df3.Firm3 = firm3
df3


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [119]:
firm2.dropna(inplace=True)
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [120]:
nadeleted = firm2.dropna()
nadeleted

90    14.0
92     9.0
93    13.0
94     5.0
dtype: float64

In [122]:
df4=df3.dropna(axis=1)
df4

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In case of DataFrame, <b>if you use dropna, it deletes entire row by default</b>. Another way is to drop only <b>those rows that are all NA</b>. If you want to <b>drop columns, pass axis=1</b>

In [123]:
cleandf3 = df3.dropna(axis=1)          # Drop row if any value in the row is NaN
cleandf3

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [124]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [125]:
clean2 = df3.dropna(how='any')   # Drop row if all values in the row are NaN
clean2

Firm1  Firm2  Firm3
93      8   13.0   10.0
94      9    5.0   12.0

In [126]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [128]:
columndrop = df3.dropna(axis=1,how='all')   # Drop column if any value in the column is NaN
columndrop

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [129]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [132]:
thresholddf = df3.dropna(axis=1,thresh=5)    
thresholddf

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [133]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [134]:
fillna1 = df3.fillna(0)      # Fill all NaN values with 0
fillna1

Firm1  Firm2  Firm3
90      8   14.0    0.0
91      9    0.0    0.0
92      7    9.0    0.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    0.0   13.0

In [136]:
print (df3)
fillna2 = df3.fillna({'Firm1':8, 'Firm2': 10})   # We can specify what value should be replaced
fillna2

    Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9   10.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11   10.0   13.0

In [138]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [139]:
fillna3 = df3.fillna(method='bfill')    # Forward fill NaNs for 1 level. Check Firm 2 -> 14 & 5
fillna3

Firm1  Firm2  Firm3
90      8   14.0   10.0
91      9    9.0   10.0
92      7    9.0   10.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [140]:
print (df3)
fillna4 = df3.fillna(method='ffill')    # Back fill NaNs till 2 levels before. Check how Firm3 behaves
fillna4

    Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    5.0   13.0

In [137]:
#print(df3.mean())
print (df3)
fillna5 = df3.fillna(round(df3.mean()))  # We will substitute empty values with Mean of the Firm in concern
fillna5

    Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0


Firm1  Firm2  Firm3
90      8   14.0   12.0
91      9   10.0   12.0
92      7    9.0   12.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11   10.0   13.0

**Merging Data**
<p/>Resembles Joins in database

In [149]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 8), 
                           'right_value': ['f', 'g', 'h', 'i', 'j','k']})
print(left_frame)
print('\n')
print(right_frame)

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j
5    7           k


In [142]:
pd.merge(left_frame, right_frame, on='key', how='inner')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

In [143]:
pd.merge(left_frame, right_frame, on='key', how='left')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h

In [144]:
pd.merge(left_frame, right_frame, on='key', how='right')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h
3    5        NaN           i
4    6        NaN           j

In [145]:
pd.merge(left_frame, right_frame, on='key', how='outer')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h
5    5        NaN           i
6    6        NaN           j

In [146]:
pd.concat([left_frame, right_frame])

C:\Users\tejks\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c         NaN
3    3          d         NaN
4    4          e         NaN
0    2        NaN           f
1    3        NaN           g
2    4        NaN           h
3    5        NaN           i
4    6        NaN           j

In [150]:
pd.concat([left_frame, right_frame], axis=1)

key left_value  key right_value
0  0.0          a    2           f
1  1.0          b    3           g
2  2.0          c    4           h
3  3.0          d    5           i
4  4.0          e    6           j
5  NaN        NaN    7           k